# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.11.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.11.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/stepanskovajsa/fi/pv112/project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/stepanskovajsa/fi/pv112/project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.11.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.11.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.11.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.11.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.11.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.11.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.11.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.11.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/stepanskovajsa/fi/pv112/project/CMakeFiles /Users/stepanskovajsa/fi/pv112/project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/stepanskovajsa/fi/pv112/project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PhobosDemo

# Build rule for target.
PhobosDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PhobosDemo
.PHONY : PhobosDemo

# fast build rule for target.
PhobosDemo/fast:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/build
.PHONY : PhobosDemo/fast

#=============================================================================
# Target rules for targets named glew

# Build rule for target.
glew: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glew
.PHONY : glew

# fast build rule for target.
glew/fast:
	$(MAKE) -f CMakeFiles/glew.dir/build.make CMakeFiles/glew.dir/build
.PHONY : glew/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f libs/glfw/src/CMakeFiles/glfw.dir/build.make libs/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named FreeImage

# Build rule for target.
FreeImage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FreeImage
.PHONY : FreeImage

# fast build rule for target.
FreeImage/fast:
	$(MAKE) -f libs/FreeImage/CMakeFiles/FreeImage.dir/build.make libs/FreeImage/CMakeFiles/FreeImage.dir/build
.PHONY : FreeImage/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/ContinuousCoverage.dir/build.make libs/tinyxml2/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/ContinuousTest.dir/build.make libs/tinyxml2/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/ContinuousBuild.dir/build.make libs/tinyxml2/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/ContinuousStart.dir/build.make libs/tinyxml2/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/ExperimentalBuild.dir/build.make libs/tinyxml2/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/ExperimentalCoverage.dir/build.make libs/tinyxml2/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/ExperimentalSubmit.dir/build.make libs/tinyxml2/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/ContinuousUpdate.dir/build.make libs/tinyxml2/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named xmltest

# Build rule for target.
xmltest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmltest
.PHONY : xmltest

# fast build rule for target.
xmltest/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/xmltest.dir/build.make libs/tinyxml2/CMakeFiles/xmltest.dir/build
.PHONY : xmltest/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/ExperimentalUpdate.dir/build.make libs/tinyxml2/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/ExperimentalStart.dir/build.make libs/tinyxml2/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/ContinuousSubmit.dir/build.make libs/tinyxml2/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/ExperimentalTest.dir/build.make libs/tinyxml2/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/NightlySubmit.dir/build.make libs/tinyxml2/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/NightlyMemCheck.dir/build.make libs/tinyxml2/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/ExperimentalConfigure.dir/build.make libs/tinyxml2/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/NightlyCoverage.dir/build.make libs/tinyxml2/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/NightlyTest.dir/build.make libs/tinyxml2/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/uninstall.dir/build.make libs/tinyxml2/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named tinyxml2

# Build rule for target.
tinyxml2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyxml2
.PHONY : tinyxml2

# fast build rule for target.
tinyxml2/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/tinyxml2.dir/build.make libs/tinyxml2/CMakeFiles/tinyxml2.dir/build
.PHONY : tinyxml2/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/ContinuousMemCheck.dir/build.make libs/tinyxml2/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/NightlyBuild.dir/build.make libs/tinyxml2/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/NightlyConfigure.dir/build.make libs/tinyxml2/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/NightlyUpdate.dir/build.make libs/tinyxml2/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/NightlyMemoryCheck.dir/build.make libs/tinyxml2/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/ContinuousConfigure.dir/build.make libs/tinyxml2/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/Nightly.dir/build.make libs/tinyxml2/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/NightlyStart.dir/build.make libs/tinyxml2/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/ExperimentalMemCheck.dir/build.make libs/tinyxml2/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/Continuous.dir/build.make libs/tinyxml2/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f libs/tinyxml2/CMakeFiles/Experimental.dir/build.make libs/tinyxml2/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named glm_static

# Build rule for target.
glm_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glm_static
.PHONY : glm_static

# fast build rule for target.
glm_static/fast:
	$(MAKE) -f libs/glm/glm/CMakeFiles/glm_static.dir/build.make libs/glm/glm/CMakeFiles/glm_static.dir/build
.PHONY : glm_static/fast

libs/glew/src/glew.o: libs/glew/src/glew.c.o

.PHONY : libs/glew/src/glew.o

# target to build an object file
libs/glew/src/glew.c.o:
	$(MAKE) -f CMakeFiles/glew.dir/build.make CMakeFiles/glew.dir/libs/glew/src/glew.c.o
.PHONY : libs/glew/src/glew.c.o

libs/glew/src/glew.i: libs/glew/src/glew.c.i

.PHONY : libs/glew/src/glew.i

# target to preprocess a source file
libs/glew/src/glew.c.i:
	$(MAKE) -f CMakeFiles/glew.dir/build.make CMakeFiles/glew.dir/libs/glew/src/glew.c.i
.PHONY : libs/glew/src/glew.c.i

libs/glew/src/glew.s: libs/glew/src/glew.c.s

.PHONY : libs/glew/src/glew.s

# target to generate assembly for a file
libs/glew/src/glew.c.s:
	$(MAKE) -f CMakeFiles/glew.dir/build.make CMakeFiles/glew.dir/libs/glew/src/glew.c.s
.PHONY : libs/glew/src/glew.c.s

src/engine/Application.o: src/engine/Application.cpp.o

.PHONY : src/engine/Application.o

# target to build an object file
src/engine/Application.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Application.cpp.o
.PHONY : src/engine/Application.cpp.o

src/engine/Application.i: src/engine/Application.cpp.i

.PHONY : src/engine/Application.i

# target to preprocess a source file
src/engine/Application.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Application.cpp.i
.PHONY : src/engine/Application.cpp.i

src/engine/Application.s: src/engine/Application.cpp.s

.PHONY : src/engine/Application.s

# target to generate assembly for a file
src/engine/Application.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Application.cpp.s
.PHONY : src/engine/Application.cpp.s

src/engine/AssetsManager.o: src/engine/AssetsManager.cpp.o

.PHONY : src/engine/AssetsManager.o

# target to build an object file
src/engine/AssetsManager.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/AssetsManager.cpp.o
.PHONY : src/engine/AssetsManager.cpp.o

src/engine/AssetsManager.i: src/engine/AssetsManager.cpp.i

.PHONY : src/engine/AssetsManager.i

# target to preprocess a source file
src/engine/AssetsManager.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/AssetsManager.cpp.i
.PHONY : src/engine/AssetsManager.cpp.i

src/engine/AssetsManager.s: src/engine/AssetsManager.cpp.s

.PHONY : src/engine/AssetsManager.s

# target to generate assembly for a file
src/engine/AssetsManager.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/AssetsManager.cpp.s
.PHONY : src/engine/AssetsManager.cpp.s

src/engine/BoundingBox.o: src/engine/BoundingBox.cpp.o

.PHONY : src/engine/BoundingBox.o

# target to build an object file
src/engine/BoundingBox.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/BoundingBox.cpp.o
.PHONY : src/engine/BoundingBox.cpp.o

src/engine/BoundingBox.i: src/engine/BoundingBox.cpp.i

.PHONY : src/engine/BoundingBox.i

# target to preprocess a source file
src/engine/BoundingBox.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/BoundingBox.cpp.i
.PHONY : src/engine/BoundingBox.cpp.i

src/engine/BoundingBox.s: src/engine/BoundingBox.cpp.s

.PHONY : src/engine/BoundingBox.s

# target to generate assembly for a file
src/engine/BoundingBox.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/BoundingBox.cpp.s
.PHONY : src/engine/BoundingBox.cpp.s

src/engine/BoxNode.o: src/engine/BoxNode.cpp.o

.PHONY : src/engine/BoxNode.o

# target to build an object file
src/engine/BoxNode.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/BoxNode.cpp.o
.PHONY : src/engine/BoxNode.cpp.o

src/engine/BoxNode.i: src/engine/BoxNode.cpp.i

.PHONY : src/engine/BoxNode.i

# target to preprocess a source file
src/engine/BoxNode.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/BoxNode.cpp.i
.PHONY : src/engine/BoxNode.cpp.i

src/engine/BoxNode.s: src/engine/BoxNode.cpp.s

.PHONY : src/engine/BoxNode.s

# target to generate assembly for a file
src/engine/BoxNode.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/BoxNode.cpp.s
.PHONY : src/engine/BoxNode.cpp.s

src/engine/ColladaLoader.o: src/engine/ColladaLoader.cpp.o

.PHONY : src/engine/ColladaLoader.o

# target to build an object file
src/engine/ColladaLoader.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/ColladaLoader.cpp.o
.PHONY : src/engine/ColladaLoader.cpp.o

src/engine/ColladaLoader.i: src/engine/ColladaLoader.cpp.i

.PHONY : src/engine/ColladaLoader.i

# target to preprocess a source file
src/engine/ColladaLoader.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/ColladaLoader.cpp.i
.PHONY : src/engine/ColladaLoader.cpp.i

src/engine/ColladaLoader.s: src/engine/ColladaLoader.cpp.s

.PHONY : src/engine/ColladaLoader.s

# target to generate assembly for a file
src/engine/ColladaLoader.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/ColladaLoader.cpp.s
.PHONY : src/engine/ColladaLoader.cpp.s

src/engine/Font.o: src/engine/Font.cpp.o

.PHONY : src/engine/Font.o

# target to build an object file
src/engine/Font.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Font.cpp.o
.PHONY : src/engine/Font.cpp.o

src/engine/Font.i: src/engine/Font.cpp.i

.PHONY : src/engine/Font.i

# target to preprocess a source file
src/engine/Font.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Font.cpp.i
.PHONY : src/engine/Font.cpp.i

src/engine/Font.s: src/engine/Font.cpp.s

.PHONY : src/engine/Font.s

# target to generate assembly for a file
src/engine/Font.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Font.cpp.s
.PHONY : src/engine/Font.cpp.s

src/engine/Geometry.o: src/engine/Geometry.cpp.o

.PHONY : src/engine/Geometry.o

# target to build an object file
src/engine/Geometry.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Geometry.cpp.o
.PHONY : src/engine/Geometry.cpp.o

src/engine/Geometry.i: src/engine/Geometry.cpp.i

.PHONY : src/engine/Geometry.i

# target to preprocess a source file
src/engine/Geometry.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Geometry.cpp.i
.PHONY : src/engine/Geometry.cpp.i

src/engine/Geometry.s: src/engine/Geometry.cpp.s

.PHONY : src/engine/Geometry.s

# target to generate assembly for a file
src/engine/Geometry.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Geometry.cpp.s
.PHONY : src/engine/Geometry.cpp.s

src/engine/GpuProgram.o: src/engine/GpuProgram.cpp.o

.PHONY : src/engine/GpuProgram.o

# target to build an object file
src/engine/GpuProgram.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/GpuProgram.cpp.o
.PHONY : src/engine/GpuProgram.cpp.o

src/engine/GpuProgram.i: src/engine/GpuProgram.cpp.i

.PHONY : src/engine/GpuProgram.i

# target to preprocess a source file
src/engine/GpuProgram.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/GpuProgram.cpp.i
.PHONY : src/engine/GpuProgram.cpp.i

src/engine/GpuProgram.s: src/engine/GpuProgram.cpp.s

.PHONY : src/engine/GpuProgram.s

# target to generate assembly for a file
src/engine/GpuProgram.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/GpuProgram.cpp.s
.PHONY : src/engine/GpuProgram.cpp.s

src/engine/InputHandler.o: src/engine/InputHandler.cpp.o

.PHONY : src/engine/InputHandler.o

# target to build an object file
src/engine/InputHandler.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/InputHandler.cpp.o
.PHONY : src/engine/InputHandler.cpp.o

src/engine/InputHandler.i: src/engine/InputHandler.cpp.i

.PHONY : src/engine/InputHandler.i

# target to preprocess a source file
src/engine/InputHandler.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/InputHandler.cpp.i
.PHONY : src/engine/InputHandler.cpp.i

src/engine/InputHandler.s: src/engine/InputHandler.cpp.s

.PHONY : src/engine/InputHandler.s

# target to generate assembly for a file
src/engine/InputHandler.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/InputHandler.cpp.s
.PHONY : src/engine/InputHandler.cpp.s

src/engine/Model.o: src/engine/Model.cpp.o

.PHONY : src/engine/Model.o

# target to build an object file
src/engine/Model.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Model.cpp.o
.PHONY : src/engine/Model.cpp.o

src/engine/Model.i: src/engine/Model.cpp.i

.PHONY : src/engine/Model.i

# target to preprocess a source file
src/engine/Model.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Model.cpp.i
.PHONY : src/engine/Model.cpp.i

src/engine/Model.s: src/engine/Model.cpp.s

.PHONY : src/engine/Model.s

# target to generate assembly for a file
src/engine/Model.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Model.cpp.s
.PHONY : src/engine/Model.cpp.s

src/engine/ModelNode.o: src/engine/ModelNode.cpp.o

.PHONY : src/engine/ModelNode.o

# target to build an object file
src/engine/ModelNode.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/ModelNode.cpp.o
.PHONY : src/engine/ModelNode.cpp.o

src/engine/ModelNode.i: src/engine/ModelNode.cpp.i

.PHONY : src/engine/ModelNode.i

# target to preprocess a source file
src/engine/ModelNode.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/ModelNode.cpp.i
.PHONY : src/engine/ModelNode.cpp.i

src/engine/ModelNode.s: src/engine/ModelNode.cpp.s

.PHONY : src/engine/ModelNode.s

# target to generate assembly for a file
src/engine/ModelNode.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/ModelNode.cpp.s
.PHONY : src/engine/ModelNode.cpp.s

src/engine/Particle.o: src/engine/Particle.cpp.o

.PHONY : src/engine/Particle.o

# target to build an object file
src/engine/Particle.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Particle.cpp.o
.PHONY : src/engine/Particle.cpp.o

src/engine/Particle.i: src/engine/Particle.cpp.i

.PHONY : src/engine/Particle.i

# target to preprocess a source file
src/engine/Particle.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Particle.cpp.i
.PHONY : src/engine/Particle.cpp.i

src/engine/Particle.s: src/engine/Particle.cpp.s

.PHONY : src/engine/Particle.s

# target to generate assembly for a file
src/engine/Particle.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Particle.cpp.s
.PHONY : src/engine/Particle.cpp.s

src/engine/ParticleSystem.o: src/engine/ParticleSystem.cpp.o

.PHONY : src/engine/ParticleSystem.o

# target to build an object file
src/engine/ParticleSystem.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/ParticleSystem.cpp.o
.PHONY : src/engine/ParticleSystem.cpp.o

src/engine/ParticleSystem.i: src/engine/ParticleSystem.cpp.i

.PHONY : src/engine/ParticleSystem.i

# target to preprocess a source file
src/engine/ParticleSystem.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/ParticleSystem.cpp.i
.PHONY : src/engine/ParticleSystem.cpp.i

src/engine/ParticleSystem.s: src/engine/ParticleSystem.cpp.s

.PHONY : src/engine/ParticleSystem.s

# target to generate assembly for a file
src/engine/ParticleSystem.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/ParticleSystem.cpp.s
.PHONY : src/engine/ParticleSystem.cpp.s

src/engine/Renderer.o: src/engine/Renderer.cpp.o

.PHONY : src/engine/Renderer.o

# target to build an object file
src/engine/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Renderer.cpp.o
.PHONY : src/engine/Renderer.cpp.o

src/engine/Renderer.i: src/engine/Renderer.cpp.i

.PHONY : src/engine/Renderer.i

# target to preprocess a source file
src/engine/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Renderer.cpp.i
.PHONY : src/engine/Renderer.cpp.i

src/engine/Renderer.s: src/engine/Renderer.cpp.s

.PHONY : src/engine/Renderer.s

# target to generate assembly for a file
src/engine/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Renderer.cpp.s
.PHONY : src/engine/Renderer.cpp.s

src/engine/Scene.o: src/engine/Scene.cpp.o

.PHONY : src/engine/Scene.o

# target to build an object file
src/engine/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Scene.cpp.o
.PHONY : src/engine/Scene.cpp.o

src/engine/Scene.i: src/engine/Scene.cpp.i

.PHONY : src/engine/Scene.i

# target to preprocess a source file
src/engine/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Scene.cpp.i
.PHONY : src/engine/Scene.cpp.i

src/engine/Scene.s: src/engine/Scene.cpp.s

.PHONY : src/engine/Scene.s

# target to generate assembly for a file
src/engine/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Scene.cpp.s
.PHONY : src/engine/Scene.cpp.s

src/engine/SceneNode.o: src/engine/SceneNode.cpp.o

.PHONY : src/engine/SceneNode.o

# target to build an object file
src/engine/SceneNode.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/SceneNode.cpp.o
.PHONY : src/engine/SceneNode.cpp.o

src/engine/SceneNode.i: src/engine/SceneNode.cpp.i

.PHONY : src/engine/SceneNode.i

# target to preprocess a source file
src/engine/SceneNode.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/SceneNode.cpp.i
.PHONY : src/engine/SceneNode.cpp.i

src/engine/SceneNode.s: src/engine/SceneNode.cpp.s

.PHONY : src/engine/SceneNode.s

# target to generate assembly for a file
src/engine/SceneNode.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/SceneNode.cpp.s
.PHONY : src/engine/SceneNode.cpp.s

src/engine/Texture.o: src/engine/Texture.cpp.o

.PHONY : src/engine/Texture.o

# target to build an object file
src/engine/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Texture.cpp.o
.PHONY : src/engine/Texture.cpp.o

src/engine/Texture.i: src/engine/Texture.cpp.i

.PHONY : src/engine/Texture.i

# target to preprocess a source file
src/engine/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Texture.cpp.i
.PHONY : src/engine/Texture.cpp.i

src/engine/Texture.s: src/engine/Texture.cpp.s

.PHONY : src/engine/Texture.s

# target to generate assembly for a file
src/engine/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/Texture.cpp.s
.PHONY : src/engine/Texture.cpp.s

src/engine/TextureLoader.o: src/engine/TextureLoader.cpp.o

.PHONY : src/engine/TextureLoader.o

# target to build an object file
src/engine/TextureLoader.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/TextureLoader.cpp.o
.PHONY : src/engine/TextureLoader.cpp.o

src/engine/TextureLoader.i: src/engine/TextureLoader.cpp.i

.PHONY : src/engine/TextureLoader.i

# target to preprocess a source file
src/engine/TextureLoader.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/TextureLoader.cpp.i
.PHONY : src/engine/TextureLoader.cpp.i

src/engine/TextureLoader.s: src/engine/TextureLoader.cpp.s

.PHONY : src/engine/TextureLoader.s

# target to generate assembly for a file
src/engine/TextureLoader.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/TextureLoader.cpp.s
.PHONY : src/engine/TextureLoader.cpp.s

src/engine/UIImage.o: src/engine/UIImage.cpp.o

.PHONY : src/engine/UIImage.o

# target to build an object file
src/engine/UIImage.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/UIImage.cpp.o
.PHONY : src/engine/UIImage.cpp.o

src/engine/UIImage.i: src/engine/UIImage.cpp.i

.PHONY : src/engine/UIImage.i

# target to preprocess a source file
src/engine/UIImage.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/UIImage.cpp.i
.PHONY : src/engine/UIImage.cpp.i

src/engine/UIImage.s: src/engine/UIImage.cpp.s

.PHONY : src/engine/UIImage.s

# target to generate assembly for a file
src/engine/UIImage.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/UIImage.cpp.s
.PHONY : src/engine/UIImage.cpp.s

src/engine/UILabel.o: src/engine/UILabel.cpp.o

.PHONY : src/engine/UILabel.o

# target to build an object file
src/engine/UILabel.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/UILabel.cpp.o
.PHONY : src/engine/UILabel.cpp.o

src/engine/UILabel.i: src/engine/UILabel.cpp.i

.PHONY : src/engine/UILabel.i

# target to preprocess a source file
src/engine/UILabel.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/UILabel.cpp.i
.PHONY : src/engine/UILabel.cpp.i

src/engine/UILabel.s: src/engine/UILabel.cpp.s

.PHONY : src/engine/UILabel.s

# target to generate assembly for a file
src/engine/UILabel.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/UILabel.cpp.s
.PHONY : src/engine/UILabel.cpp.s

src/engine/UIManager.o: src/engine/UIManager.cpp.o

.PHONY : src/engine/UIManager.o

# target to build an object file
src/engine/UIManager.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/UIManager.cpp.o
.PHONY : src/engine/UIManager.cpp.o

src/engine/UIManager.i: src/engine/UIManager.cpp.i

.PHONY : src/engine/UIManager.i

# target to preprocess a source file
src/engine/UIManager.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/UIManager.cpp.i
.PHONY : src/engine/UIManager.cpp.i

src/engine/UIManager.s: src/engine/UIManager.cpp.s

.PHONY : src/engine/UIManager.s

# target to generate assembly for a file
src/engine/UIManager.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/UIManager.cpp.s
.PHONY : src/engine/UIManager.cpp.s

src/engine/UINode.o: src/engine/UINode.cpp.o

.PHONY : src/engine/UINode.o

# target to build an object file
src/engine/UINode.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/UINode.cpp.o
.PHONY : src/engine/UINode.cpp.o

src/engine/UINode.i: src/engine/UINode.cpp.i

.PHONY : src/engine/UINode.i

# target to preprocess a source file
src/engine/UINode.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/UINode.cpp.i
.PHONY : src/engine/UINode.cpp.i

src/engine/UINode.s: src/engine/UINode.cpp.s

.PHONY : src/engine/UINode.s

# target to generate assembly for a file
src/engine/UINode.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/UINode.cpp.s
.PHONY : src/engine/UINode.cpp.s

src/engine/VertexBuffer.o: src/engine/VertexBuffer.cpp.o

.PHONY : src/engine/VertexBuffer.o

# target to build an object file
src/engine/VertexBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/VertexBuffer.cpp.o
.PHONY : src/engine/VertexBuffer.cpp.o

src/engine/VertexBuffer.i: src/engine/VertexBuffer.cpp.i

.PHONY : src/engine/VertexBuffer.i

# target to preprocess a source file
src/engine/VertexBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/VertexBuffer.cpp.i
.PHONY : src/engine/VertexBuffer.cpp.i

src/engine/VertexBuffer.s: src/engine/VertexBuffer.cpp.s

.PHONY : src/engine/VertexBuffer.s

# target to generate assembly for a file
src/engine/VertexBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/VertexBuffer.cpp.s
.PHONY : src/engine/VertexBuffer.cpp.s

src/engine/utils.o: src/engine/utils.cpp.o

.PHONY : src/engine/utils.o

# target to build an object file
src/engine/utils.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/utils.cpp.o
.PHONY : src/engine/utils.cpp.o

src/engine/utils.i: src/engine/utils.cpp.i

.PHONY : src/engine/utils.i

# target to preprocess a source file
src/engine/utils.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/utils.cpp.i
.PHONY : src/engine/utils.cpp.i

src/engine/utils.s: src/engine/utils.cpp.s

.PHONY : src/engine/utils.s

# target to generate assembly for a file
src/engine/utils.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/engine/utils.cpp.s
.PHONY : src/engine/utils.cpp.s

src/game/Background.o: src/game/Background.cpp.o

.PHONY : src/game/Background.o

# target to build an object file
src/game/Background.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/game/Background.cpp.o
.PHONY : src/game/Background.cpp.o

src/game/Background.i: src/game/Background.cpp.i

.PHONY : src/game/Background.i

# target to preprocess a source file
src/game/Background.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/game/Background.cpp.i
.PHONY : src/game/Background.cpp.i

src/game/Background.s: src/game/Background.cpp.s

.PHONY : src/game/Background.s

# target to generate assembly for a file
src/game/Background.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/game/Background.cpp.s
.PHONY : src/game/Background.cpp.s

src/game/Hud.o: src/game/Hud.cpp.o

.PHONY : src/game/Hud.o

# target to build an object file
src/game/Hud.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/game/Hud.cpp.o
.PHONY : src/game/Hud.cpp.o

src/game/Hud.i: src/game/Hud.cpp.i

.PHONY : src/game/Hud.i

# target to preprocess a source file
src/game/Hud.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/game/Hud.cpp.i
.PHONY : src/game/Hud.cpp.i

src/game/Hud.s: src/game/Hud.cpp.s

.PHONY : src/game/Hud.s

# target to generate assembly for a file
src/game/Hud.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/game/Hud.cpp.s
.PHONY : src/game/Hud.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/PhobosDemo.dir/build.make CMakeFiles/PhobosDemo.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... PhobosDemo"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... glew"
	@echo "... glfw"
	@echo "... FreeImage"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousTest"
	@echo "... ContinuousBuild"
	@echo "... ContinuousStart"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalSubmit"
	@echo "... ContinuousUpdate"
	@echo "... xmltest"
	@echo "... ExperimentalUpdate"
	@echo "... ExperimentalStart"
	@echo "... ContinuousSubmit"
	@echo "... ExperimentalTest"
	@echo "... NightlySubmit"
	@echo "... NightlyMemCheck"
	@echo "... ExperimentalConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyTest"
	@echo "... uninstall"
	@echo "... tinyxml2"
	@echo "... ContinuousMemCheck"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyUpdate"
	@echo "... NightlyMemoryCheck"
	@echo "... ContinuousConfigure"
	@echo "... Nightly"
	@echo "... NightlyStart"
	@echo "... ExperimentalMemCheck"
	@echo "... Continuous"
	@echo "... Experimental"
	@echo "... glm_static"
	@echo "... libs/glew/src/glew.o"
	@echo "... libs/glew/src/glew.i"
	@echo "... libs/glew/src/glew.s"
	@echo "... src/engine/Application.o"
	@echo "... src/engine/Application.i"
	@echo "... src/engine/Application.s"
	@echo "... src/engine/AssetsManager.o"
	@echo "... src/engine/AssetsManager.i"
	@echo "... src/engine/AssetsManager.s"
	@echo "... src/engine/BoundingBox.o"
	@echo "... src/engine/BoundingBox.i"
	@echo "... src/engine/BoundingBox.s"
	@echo "... src/engine/BoxNode.o"
	@echo "... src/engine/BoxNode.i"
	@echo "... src/engine/BoxNode.s"
	@echo "... src/engine/ColladaLoader.o"
	@echo "... src/engine/ColladaLoader.i"
	@echo "... src/engine/ColladaLoader.s"
	@echo "... src/engine/Font.o"
	@echo "... src/engine/Font.i"
	@echo "... src/engine/Font.s"
	@echo "... src/engine/Geometry.o"
	@echo "... src/engine/Geometry.i"
	@echo "... src/engine/Geometry.s"
	@echo "... src/engine/GpuProgram.o"
	@echo "... src/engine/GpuProgram.i"
	@echo "... src/engine/GpuProgram.s"
	@echo "... src/engine/InputHandler.o"
	@echo "... src/engine/InputHandler.i"
	@echo "... src/engine/InputHandler.s"
	@echo "... src/engine/Model.o"
	@echo "... src/engine/Model.i"
	@echo "... src/engine/Model.s"
	@echo "... src/engine/ModelNode.o"
	@echo "... src/engine/ModelNode.i"
	@echo "... src/engine/ModelNode.s"
	@echo "... src/engine/Particle.o"
	@echo "... src/engine/Particle.i"
	@echo "... src/engine/Particle.s"
	@echo "... src/engine/ParticleSystem.o"
	@echo "... src/engine/ParticleSystem.i"
	@echo "... src/engine/ParticleSystem.s"
	@echo "... src/engine/Renderer.o"
	@echo "... src/engine/Renderer.i"
	@echo "... src/engine/Renderer.s"
	@echo "... src/engine/Scene.o"
	@echo "... src/engine/Scene.i"
	@echo "... src/engine/Scene.s"
	@echo "... src/engine/SceneNode.o"
	@echo "... src/engine/SceneNode.i"
	@echo "... src/engine/SceneNode.s"
	@echo "... src/engine/Texture.o"
	@echo "... src/engine/Texture.i"
	@echo "... src/engine/Texture.s"
	@echo "... src/engine/TextureLoader.o"
	@echo "... src/engine/TextureLoader.i"
	@echo "... src/engine/TextureLoader.s"
	@echo "... src/engine/UIImage.o"
	@echo "... src/engine/UIImage.i"
	@echo "... src/engine/UIImage.s"
	@echo "... src/engine/UILabel.o"
	@echo "... src/engine/UILabel.i"
	@echo "... src/engine/UILabel.s"
	@echo "... src/engine/UIManager.o"
	@echo "... src/engine/UIManager.i"
	@echo "... src/engine/UIManager.s"
	@echo "... src/engine/UINode.o"
	@echo "... src/engine/UINode.i"
	@echo "... src/engine/UINode.s"
	@echo "... src/engine/VertexBuffer.o"
	@echo "... src/engine/VertexBuffer.i"
	@echo "... src/engine/VertexBuffer.s"
	@echo "... src/engine/utils.o"
	@echo "... src/engine/utils.i"
	@echo "... src/engine/utils.s"
	@echo "... src/game/Background.o"
	@echo "... src/game/Background.i"
	@echo "... src/game/Background.s"
	@echo "... src/game/Hud.o"
	@echo "... src/game/Hud.i"
	@echo "... src/game/Hud.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

