# CMake generated Testfile for 
# Source directory: /Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx
# Build directory: /Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-gtx "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx")
add_test(test-gtx_associated_min_max "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_associated_min_max")
add_test(test-gtx_closest_point "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_closest_point")
add_test(test-gtx_color_encoding "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_color_encoding")
add_test(test-gtx_color_space_YCoCg "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_color_space_YCoCg")
add_test(test-gtx_color_space "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_color_space")
add_test(test-gtx_common "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_common")
add_test(test-gtx_compatibility "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_compatibility")
add_test(test-gtx_component_wise "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_component_wise")
add_test(test-gtx_easing "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_easing")
add_test(test-gtx_euler_angle "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_euler_angle")
add_test(test-gtx_extend "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_extend")
add_test(test-gtx_extended_min_max "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_extended_min_max")
add_test(test-gtx_exterior_product "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_exterior_product")
add_test(test-gtx_fast_exponential "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_fast_exponential")
add_test(test-gtx_fast_square_root "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_fast_square_root")
add_test(test-gtx_fast_trigonometry "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_fast_trigonometry")
add_test(test-gtx_functions "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_functions")
add_test(test-gtx_gradient_paint "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_gradient_paint")
add_test(test-gtx_handed_coordinate_space "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_handed_coordinate_space")
add_test(test-gtx_integer "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_integer")
add_test(test-gtx_intersect "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_intersect")
add_test(test-gtx_io "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_io")
add_test(test-gtx_load "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_load")
add_test(test-gtx_log_base "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_log_base")
add_test(test-gtx_matrix_cross_product "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_matrix_cross_product")
add_test(test-gtx_matrix_decompose "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_matrix_decompose")
add_test(test-gtx_matrix_factorisation "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_matrix_factorisation")
add_test(test-gtx_matrix_interpolation "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_matrix_interpolation")
add_test(test-gtx_matrix_major_storage "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_matrix_major_storage")
add_test(test-gtx_matrix_operation "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_matrix_operation")
add_test(test-gtx_matrix_query "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_matrix_query")
add_test(test-gtx_matrix_transform_2d "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_matrix_transform_2d")
add_test(test-gtx_norm "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_norm")
add_test(test-gtx_normal "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_normal")
add_test(test-gtx_normalize_dot "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_normalize_dot")
add_test(test-gtx_number_precision "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_number_precision")
add_test(test-gtx_orthonormalize "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_orthonormalize")
add_test(test-gtx_optimum_pow "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_optimum_pow")
add_test(test-gtx_perpendicular "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_perpendicular")
add_test(test-gtx_polar_coordinates "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_polar_coordinates")
add_test(test-gtx_projection "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_projection")
add_test(test-gtx_quaternion "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_quaternion")
add_test(test-gtx_dual_quaternion "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_dual_quaternion")
add_test(test-gtx_range "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_range")
add_test(test-gtx_rotate_normalized_axis "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_rotate_normalized_axis")
add_test(test-gtx_rotate_vector "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_rotate_vector")
add_test(test-gtx_scalar_multiplication "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_scalar_multiplication")
add_test(test-gtx_scalar_relational "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_scalar_relational")
add_test(test-gtx_spline "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_spline")
add_test(test-gtx_string_cast "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_string_cast")
add_test(test-gtx_texture "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_texture")
add_test(test-gtx_type_aligned "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_type_aligned")
add_test(test-gtx_type_trait "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_type_trait")
add_test(test-gtx_vec_swizzle "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_vec_swizzle")
add_test(test-gtx_vector_angle "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_vector_angle")
add_test(test-gtx_vector_query "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_vector_query")
add_test(test-gtx_wrap "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/gtx/test-gtx_wrap")
