# CMake generated Testfile for 
# Source directory: /Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core
# Build directory: /Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-core_cpp_constexpr "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_cpp_constexpr")
add_test(test-core_cpp_defaulted_ctor "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_cpp_defaulted_ctor")
add_test(test-core_force_aligned_gentypes "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_force_aligned_gentypes")
add_test(test-core_force_ctor_init "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_force_ctor_init")
add_test(test-core_force_explicit_ctor "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_force_explicit_ctor")
add_test(test-core_force_inline "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_force_inline")
add_test(test-core_force_pure "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_force_pure")
add_test(test-core_force_unrestricted_gentype "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_force_unrestricted_gentype")
add_test(test-core_force_xyzw_only "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_force_xyzw_only")
add_test(test-core_type_aligned "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_type_aligned")
add_test(test-core_type_cast "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_type_cast")
add_test(test-core_type_ctor "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_type_ctor")
add_test(test-core_type_int "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_type_int")
add_test(test-core_type_length "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_type_length")
add_test(test-core_type_mat2x2 "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_type_mat2x2")
add_test(test-core_type_mat2x3 "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_type_mat2x3")
add_test(test-core_type_mat2x4 "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_type_mat2x4")
add_test(test-core_type_mat3x2 "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_type_mat3x2")
add_test(test-core_type_mat3x3 "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_type_mat3x3")
add_test(test-core_type_mat3x4 "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_type_mat3x4")
add_test(test-core_type_mat4x2 "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_type_mat4x2")
add_test(test-core_type_mat4x3 "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_type_mat4x3")
add_test(test-core_type_mat4x4 "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_type_mat4x4")
add_test(test-core_type_vec1 "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_type_vec1")
add_test(test-core_type_vec2 "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_type_vec2")
add_test(test-core_type_vec3 "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_type_vec3")
add_test(test-core_type_vec4 "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_type_vec4")
add_test(test-core_func_common "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_func_common")
add_test(test-core_func_exponential "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_func_exponential")
add_test(test-core_func_geometric "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_func_geometric")
add_test(test-core_func_integer "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_func_integer")
add_test(test-core_func_integer_bit_count "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_func_integer_bit_count")
add_test(test-core_func_integer_find_lsb "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_func_integer_find_lsb")
add_test(test-core_func_integer_find_msb "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_func_integer_find_msb")
add_test(test-core_func_matrix "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_func_matrix")
add_test(test-core_func_noise "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_func_noise")
add_test(test-core_func_packing "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_func_packing")
add_test(test-core_func_trigonometric "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_func_trigonometric")
add_test(test-core_func_vector_relational "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_func_vector_relational")
add_test(test-core_func_swizzle "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_func_swizzle")
add_test(test-core_setup_force_cxx98 "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_setup_force_cxx98")
add_test(test-core_setup_force_size_t_length "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_setup_force_size_t_length")
add_test(test-core_setup_message "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_setup_message")
add_test(test-core_setup_platform_unknown "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_setup_platform_unknown")
add_test(test-core_setup_precision "/Users/stepanskovajsa/fi/pv112/project/libs/glm/test/core/test-core_setup_precision")
